# Controls when the action will run. Triggers the workflow on push request for the master branch
on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to LeanEngine
      uses: enflo/curl-action@v1.2
      with:
        curl: -X POST https://cn-n1-console-api.leancloud.cn/1.1/engine/groups/web/production/version?gitTag=master&token=KGka8Rm3rU2up6Js0RtNx1wu3Wk5SvOBLRqxmNv49pd0L5vtcLVMUI624xvrONQ2
